name: shop_apllication_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  file_picker: ^8.0.6
  jwt_decoder: ^2.0.1
  jwt_decode: ^0.3.1
  shared_preferences: ^2.2.3
  aws_sdk: ^0.0.3
  image_picker: ^1.1.2
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.1
  image: ^4.2.0
  path_provider: ^2.1.3
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  flutter_screenutil: ^5.9.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  

flutter:
  uses-material-design: true

  assets:
   - assets1/splash.jpeg
   - assets1/logo.png
   - assets1/logo1.png
   - assets1/background.jpg
   - assets1/icon_home.png
   - assets1/icon_menu.png
   - assets1/iconTMZ.png
   - assets1/icon_model.png
   - assets1/icon_product.png
   - assets1/icon_materials.png
   - assets1/icon minus.png
   - assets1/icon_journal.png
   - assets1/icon_zakazy.png
   - assets1/icon_product2.png
   - assets1/background2.jpg
   - assets1/arrowBack.png